### ISSUE TITLE
Optical photon tracking causes geometry boundary hits to be missed

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#150]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): feature-geomBoundary (at least, probably all branches)
- revision (HEAD for most recent): HEAD
- OS or system: Ubuntu 16.04, parity.physics.wm.edu
- Special ROOT or Geant4 versions? ROOT 6.14/00 and geant4.10.04.p01

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. `git reset 04e1c807c9b0a4beacad988ae4ffae23ca445d47`
2. `build/remoll -t 1 macros/issues/issue150_1.mac`
3. `build/remoll -t 1 macros/issues/issue150_2.mac`
4. `root -l remollout_Mainz_1.root -e 'T->Draw("hit.z","hit.det == 50002 && hit.pid == 11")'`
5. `root -l remollout_Mainz_2.root -e 'T->Draw("hit.z","hit.det == 50002 && hit.pid == 11")'`

### Expected Result: (what do you expect when you execute the steps above)
Since the only difference is the simulation of optical photons, the number of entries in each of the outputs above should be identical to each other and to 100.

### Actual Result: (what do you get when you execute the steps above)
The first output of `macros/issue150_1.mac` is only 10% of the hits. The only difference is `/remoll/physlist/optical/enable`.

**Comment by wdconinc** [comment]
A fun read: https://arxiv.org/pdf/1612.05162.pdf, "Peculiarities in the Simulation of Optical Physics with Geant4"

**Comment by wdconinc** [comment]
Actually "fun" -> "recommended"

**Comment by wdconinc** [comment]
A slightly longer read: http://publications.rwth-aachen.de/record/667646/files/667646.pdf (dissertation)

**Comment by cameronc137** [comment]
Related question coming from Qsim comparison of optical vs. no optical photon processes in physics list using the same macro-set seed and getting different results:

Is it the case that the "seed" that is set will define a long list of sub-seed numbers that are used in the creation of a gun-event electron? If so, then does geant work its way through this list for each gun-event only, or for each gun-event plus also secondary particle creation? Thus, if you chose to include optical processes would you expect the numbers in this sub-seed list that are used for each new gun-event electron to be different than in the case of not including optical processes, since the multitude of optical photons are getting tracked and consuming the next entries in the list of numbers used for new gun-events + secondaries? Am I close in my understanding of seeds and geant processes?

**Comment by wdconinc** [comment]
It should start each event from the same seed but yeah I think some of the randomness can indeed cause differences between different physics lists.

**Comment by wdconinc** [comment]
Re: random number sequences: http://hypernews.slac.stanford.edu/HyperNews/geant4/get/eventtrackmanage/1072/3/1.html

**Comment by wdconinc** [comment]
Tries that went nowhere:
- Use G4Step::IsFirstStepInVolume(): also set to true for subsequent steps after photon emission

**Comment by wdconinc** [comment]
Some progress...

With optical photons:
![image](https://user-images.githubusercontent.com/4656391/44426834-c0ccf800-a55d-11e8-9854-22a75cb2d872.png)

Without optical photons:
![image](https://user-images.githubusercontent.com/4656391/44426847-c9bdc980-a55d-11e8-8c50-a73886632007.png)

**Comment by wdconinc** [comment]
I think fixed in feature-geomBoundary 3054d19. @cameronc137 please test?

**Comment by wdconinc** [comment]
Resolved and merged in develop.
