### ISSUE TITLE
Kryptonite material energy deposit is wrong

### ISSUE THREAD

**Issue by rakithab** [JeffersonLab/remoll#172]
### Environment: (where does this bug occur, have you tried other environments)
- develop branch
-  revision HEAD
-  OS or system:
-  Special ROOT or Geant4 versions? geant4.10.03 and root-6.08.00

### Steps to reproduce: (give a step by step account of how to trigger the bug)
Add a volume with Kryptonite material

### Expected Result: (what do you expect when you execute the steps above)
the energy deposit in the volume should match the energy of incident particles as Kryptonite absorb all the energy into it.

### Actual Result: (what do you get when you execute the steps above)
I do not see 100% energy deposited in the volume. see attached plots
![moller_det28_hit_e](https://user-images.githubusercontent.com/609625/50354673-e5d47600-0511-11e9-8f17-e00e6413f6f7.png)
![moller_det28_hit_edep](https://user-images.githubusercontent.com/609625/50354674-e5d47600-0511-11e9-803c-a3564c879904.png)

**Comment by cameronc137** [comment]
I think that the hit.edep variable is still computed as a one-of-many steps in a volume kind of parameter, so it may be that it is simply calculating the energy deposited in that first step, and since after that step is done the entire track is killed, it doesn't continue stepping and depositing the rest of its energy as it would in a non-kryptonite scenario. Is this behavior here new, or has it always been this way? 

It may be possible to modify the way the kryptonite functionality is implemented to set the momentum to zero during that initial step, and then kill the track afterward, so that the edep calcuator sees that the energy has been absorbed by the material.

**Comment by wdconinc** [comment]
So I guess the problem here is the following:
- when using full materials (e.g. G4_Pb), which is slow, we get the following hits in a block of materials:
```

**Comment by wdconinc** [comment]
@rakithab Can you confirm my analysis above?

**Comment by wdconinc** [comment]
One might also wonder why in the simulation with kryptonite disabled the sum of hit deposited energies does not agree with the sum object...
```
Lead
hit: 0.248528 1.00168 0.177117 0.708875 1.04138 2.35246 0.771421 1.04193 0.39859 0.207792 0.385388 0.115256 0.0895066 0.333686 0.0945081 1.29056 0.151861 0.00326835 0.786009 0.141089 0.211897 0.0677711 0.62591 0.845629 3.03782 1.74259 0.767775 0.657293 0.0410553 0.374961 0.58613 0.162286 1.36637 0.545316 0.122725 0.317257 1.0952 0.974934 0.00636254 0.353013 0.0706354 2.56494 0.929451 2.48095 0.426616 0.374828 1.15784 1.45979 0.00780941 1.10931 0.0975556 1.3174 2.61805 0.486992 0.493074 0.586268 0.0995624 0.631063 1.21025 1.84226 1.01236 MeV
hit sum = 46.2202 MeV
sum: 10558.9 MeV
```

**Comment by wdconinc** [comment]
Ok, so at least user limits now (develop 6472f34689e687834670d1d1aa77f54f4e4ec29b) is acting correctly: all energy in a single hit.
```
Processing analysis/issues/issue172.C...
Lead
hit: 2.79084 0.250722 0.126983 0.751546 0.689868 0.136596 0.169301 1.72661 0.695538 0.00539331 0.232751 0.0403262 0.136237 0.624287 0.344374 0.638755 0.684848 0.231549 0.831656 1.49825 0.16947 0.233465 0.031472 0.214394 0.572451 0.593841 0.919408 0.0527639 0.66293 0.281838 0.386466 0.69345 0.653826 0.206384 0.727071 0.923065 1.09825 3.8036 0.773688 1.65728 4.2843 1.58518 0.969855 1.89878 2.54394 3.02038 0.554339 MeV
hit sum = 42.1183 MeV
sum: 10568.9 MeV
Krypt
hit: 2.79084 MeV
hit sum = 2.79084 MeV
sum: 3.43182 MeV
Userlimits
hit: 10999.5 MeV
hit sum = 10999.5 MeV
sum: 10999.5 MeV
```

@rakithab In the short term you may want to use user limits instead of kryptonite, if this is time sensitive. I will probably get kryptonite to use user limits too but with the previous materials-defined properties instead of it being a volume-defined property.

Remaining questions:
- why isn't sum.edep equal to sum over hit.edep?

**Comment by wdconinc** [comment]
So, now (develop 61a8f7) we have both working kryptonite, userlimit and detector sums:
```
Processing analysis/issues/issue172.C...
Lead (all)
hit: 2.79084 0.250722 0.126983 0.751546 0.689868 0.136596 ... (hundreds of little hits) ... 0.304181 MeV
hit sum = 10971.5 MeV
sum: 10971.5 MeV
Lead
hit: 2.79084 0.250722 0.126983 0.751546 0.689868 0.136596 0.169301 1.72661 0.695538 0.00539331 0.232751 0.0403262 0.136237 0.624287 0.344374 0.638755 0.684848 0.231549 0.831656 1.49825 0.16947 0.233465 0.031472 0.214394 0.572451 0.593841 0.919408 0.0527639 0.66293 0.281838 0.386466 0.69345 0.653826 0.206384 0.727071 0.923065 1.09825 3.8036 0.773688 1.65728 4.2843 1.58518 0.969855 1.89878 2.54394 3.02038 0.554339 MeV
hit sum = 42.1183 MeV
sum: 10971.5 MeV
Krypt
hit: 10999.5 MeV
hit sum = 10999.5 MeV
sum: 10999.5 MeV
Userlimits
hit: 10999.5 MeV
hit sum = 10999.5 MeV
sum: 10999.5 MeV
```
Conclusions:
1. userlimits and kryptonite behave identical (because we are now using userlimits for kryptonite...)
2. sum over hit.edep is indeed equal to the sum.edep for kryptonite and when storing all hits
3. when not storing all hits (the default), the sum.edep is still correct
4. the default behavior for storing hits is unchanged (and a sensible balance between not writing hundreds of little hits and losing lots of energy in the showers)

Closing this issue, refer to pull request, further discussion there.
