### ISSUE TITLE
Random Number Seed

### ISSUE THREAD

**Issue by seamusriordan** [JeffersonLab/remoll#20]
Seed should be set through G4Random:: and not CLHEP::Random:: in remoll.cc

https://twiki.cern.ch/twiki/bin/view/Geant4/QuickMigrationGuideForGeant4V10#Random_numbers

**Comment by wdconinc** [comment]
If the goal is MT, then I can add that there's a lot more work to do than just changing the random generator. But at least it would be great if we could compile remoll against a geant4 installation compiled with GEANT4_BUILD_MULTITHREADED=ON... That's something this bug will hopefully fix, right? Or at least, I assume that's why you ran into it.

**Comment by seamusriordan** [comment]
Yes, full MT would be nice, but this is necessary apparently in at least some installations.  I ran across this as a problem on one of our local machines which wasn't making unique results.

**Comment by wdconinc** [comment]
This bug could be related rather to use of drand48 in https://github.com/JeffersonLab/remoll/blob/master/src/remollMultScatt.cc#L540. Using a different random number generator in this one instance is probably going to generate different results even if you keep the G4Random seed the same. I'm going to change drand48 into G4UniformRand and commit to master.
