### ISSUE TITLE
Setting kryptonite to false in macro claims to still treat tungsten and copper as kryptonite (but not lead)

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/remoll#61]
When changing the macro kryponite setting to false these lines (and a random number of them, always appearing in such pairs) appear at runtime, suggesting that kryptonite is being set to true (I'm not sure the best way to verify this other than plopping a block of tungsten somewhere sensitive), contrary to the macro settings:

G4WT0 > --> Event 0 starts with initial seeds (70003157,20804345).
G4WT0 > Loading kryptonite materials table...
G4WT1 > Loading kryptonite materials table...
G4WT0 > Treating Tungsten as kryptonite.
G4WT1 > Treating Tungsten as kryptonite.
G4WT0 > Treating Copper as kryptonite.
G4WT1 > Treating Copper as kryptonite.
G4WT0 > Treating Tungsten as kryptonite.
G4WT1 > Treating Tungsten as kryptonite.
G4WT0 > Treating Copper as kryptonite.
G4WT1 > Treating Copper as kryptonite.

I do not know why lead doesn't show up here too.

This may be related to some segfault problems I am encountering elsewhere, but I cannot say for certain yet.

https://github.com/JeffersonLab/remoll/blob/c45cfb32c6dd3587eb606973a41f9f8eeca0d0a3/macros/runexample.mac#L59

**Comment by cameronc137** [comment]
Definitely the simulation runs much faster when Kryptonite is set to true, so I think it may just be a strange print statement somewhere, and not a real issue.

The true setting does not change what the "treating x as kryptonite" messages say and does not include lead either.

Regardless, something is not being communicated correctly by the print statements about the kryptonite materials list setting.

**Comment by wdconinc** [comment]
commit 52d1986

The message was "Treating Copper as kryptonite" is somewhat confusing since it only adds Copper to the list of materials that will be treated as kryptonite if so enabled with /remoll/kryptonite true.

The reason why materials appear twice is because they are defined twice: we loop over the material table and store every material with a matching name. Since Copper is defined in both geometry_sculpt/upstreamDaughter.gdml and geometry_sculpt/hybridDaughter.gdml it appears twice.

The reason by Lead does not appear is because 1) it is not used anywhere, and 2) it was included as Pb instead of Lead anyway. I've changed that to Lead. 

We should be using G4_Pb, G4_W and G4_Cu for materials. We should also have a way to add new materials through the macro interface, e.g. /remoll/kryptonite true, /remoll/treataskryptonite G4_Pb

**Comment by wdconinc** [comment]
commit f77c025795c83845ed3ed8d30f5f54a19bb03a60

Now use `/remoll/kryptonite/set true` instead of `/remoll/kryptonite true`

There are other commands in `/remoll/kryptonite/`
